### ISSUE TITLE
【bug】长时间挂着之后无反应重启出现异常

### ISSUE THREAD

**Issue by xiaofentai** [NatriumLab/python-mirai#102]
异常:
System.ArgumentOutOfRangeException: 该值必须大于或等于零，且必须小于控制台缓冲区在该维度的大小。
参数名: top
实际值是 -1。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   在 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   在 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

还有就是关于时间获取的问题（看样子似乎获取到了别的时区的时间）
![123](https://user-images.githubusercontent.com/62656473/87866226-8bcbb900-c9b1-11ea-85d5-398e9753b690.png)

**Comment by Chenwe-i-lin** [comment]
这是miraiOK的问题.
