### ISSUE TITLE
在线文档有错误...

### ISSUE THREAD

**Issue by daofeng2015** [NatriumLab/python-mirai#17]
右上角的pypi的链接有错误..估计是多打了个s
https://pypi.org/projects/kuriyama
正确的是
https://pypi.org/project/kuriyama

还有 hello world哪里已经修复了..
快更新文档吧(没有催更

**Comment by Chenwe-i-lin** [comment]
知道了.

**Comment by Chenwe-i-lin** [comment]
Fixed.
