### ISSUE TITLE
messageChain当中好像没有sender信息?

### ISSUE THREAD

**Issue by wyapx** [NatriumLab/python-mirai#18]
messageChain里面没有httpapi返回的sender信息，是要从其他地方获取还是？

**Comment by Chenwe-i-lin** [comment]
见[文档](https://mirai-py.originpages.com/tutorial/annotations.html), 这个界面会在不久的将来改进

**Comment by Chenwe-i-lin** [comment]
如果是 `FriendMessage`, 指定形参类型注释为 `mirai.Friend`, 如果是 `GroupMessage`, 则是 `mirai.Member`, 如果不确定, 指定为魔法注释 `"Sender"`

**Comment by Chenwe-i-lin** [comment]
哦 github 这狗屎的UX.
