### ISSUE TITLE
本地图片发送后是裂开的

### ISSUE THREAD

**Issue by SukiYume** [NatriumLab/python-mirai#47]
测试代码：
```
from mirai import Mirai, Image, Plain, MessageChain, Depend, Friend
import mirai
import asyncio

qq = 123456789
authKey = 'ASDFGHJ'
app = Mirai(f"mirai://localhost:8080/?authKey={authKey}&qq={qq}", websocket=True)

@app.receiver("FriendMessage")
async def handle_msg(app: Mirai, message: MessageChain, friend: Friend):
    await app.sendFriendMessage(friend, [
        Image.fromFileSystem('2.png'),
#        mirai.image.LocalImage('2.png'),
        Plain(text="!")
])
```

在收到朋友私信时发送一张本地图片（同文件夹下有一张“2.png”）。下面是Mirai console输出，显示成功发送。

>  23:34:43 [INFO] [NETWORK] Received: MessageSvc.PbGetMsg.GetMsgSuccess(messages=<Iterable>))
 23:34:43 [INFO] [NETWORK] Send done: ImgStore.GroupPicUp
 23:34:43 [INFO] [NETWORK] Received: FileExists(fileId=2768681860, fileInfo=ImgInfo(fileMd5=[-91, 40, -90, -121, 32, 125, 99, -26, -77, -120, 122, 117, -19, -72, 79, 14], fileType=1001, fileSize=13734, fileWidth=331, fileHeight=191))
 23:34:43 [INFO] [NETWORK] Send done: MessageSvc.PbSendMsg
 23:34:43 [INFO] [NETWORK] Received: MessageSvc.PbSendMsg.Response.SUCCESS
 23:34:45 [INFO] [NETWORK] Send done: Heartbeat.Alive
 23:34:45 [INFO] [NETWORK] Received: Heartbeat.Alive.Response
 23:34:47 [INFO] [NETWORK] Received: net.mamoe.mirai.qqandroid.network.protocol.data.jce.RequestPushNotify@73c69981
 23:34:47 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 23:34:47 [INFO] [NETWORK] Received: MessageSvc.PbGetMsg.GetMsgSuccess(messages=<Iterable>))

然而，实际收到的消息中的图片是裂开的（Plain text的“！”正常发送出来了）：
![image](https://user-images.githubusercontent.com/38221742/77853670-f8128900-7217-11ea-8908-b406cdd74ee7.png)

测试，把图片消息转发出来，发现QQ上图片格式是[CQ:image, file=XXXXX.jpg,url=xxxx]，然而，不管是Image.fromFileSystem还是mirai.image.LocalImage，构造出来的消息都只有[CQ:image,file=XXXX.jpg]，没有url。

想请教一下问题是出在了哪个地方？

**Comment by xy9860** [comment]
我发图片也失败了，发群里直接没反应，发好友一直转

**Comment by Chenwe-i-lin** [comment]
在: `dev` 分支, `mirai-console-wrapper:0.1.4`(`mirai-core:0.31.1`, `mirai-console:0.4.1`) 版本下未复现:  
``` python
@app.receiver("GroupMessage")
async def event_gm(app: Mirai, group: Group, member: Member):
    if member.id == MyQQ:
        await app.sendGroupMessage(group, [
            Image.fromFileSystem("E:\\Image\\00C49FCD-D8D9-4966-B2FC-F18F6220485E.jpg")
        ])
```

**Comment by Chenwe-i-lin** [comment]
由于内部是由 `pathlib.Path` 提供的文件访问支持, 本人无法找出任何问题, 请尝试升级 `mirai-core` 和 `mirai-console-wrapper`.

**Comment by Chenwe-i-lin** [comment]
顺便, 据我了解, 原始版本的 CQ 码并不会提供图片的 url, 看起来你使用的是 `cqhttp`...

**Comment by SukiYume** [comment]
（是的，我在用小号做测试，小号用的是cqhttp
这似乎是个玄学问题…
刚刚测试，私信发图片怎么也发送不了。
但是，改成群消息发图片，就能发送了。
然后，再改回原来的代码，私信发图片也就可以了。我……？？？
这样的图片消息经过cqhttp转发出来也带上url了。
所以直到问题解决了，也不知道问题出在什么地方……

**Comment by Chenwe-i-lin** [comment]
总结: 傻逼TX.

**Comment by SukiYume** [comment]
是的没错
