### ISSUE TITLE
我私聊机器人发图还是失败

### ISSUE THREAD

**Issue by xy9860** [NatriumLab/python-mirai#48]
Console-Pure Version: 0.4.1
Core Version: 0.31.4
如果是sendGroupMessage发图片没有问题，但是sendFriendMessage发图片就会一直转圈
![`@J$ECCHC{ EB_JO106V8EI](https://user-images.githubusercontent.com/25838633/78017083-578aa900-737e-11ea-9390-3d68942df903.png)
![RB})J56N~Y_B{QHP41UCXB7](https://user-images.githubusercontent.com/25838633/78017155-7426e100-737e-11ea-8d19-1ca33fab6144.png)

**Comment by xy9860** [comment]
测试发现，转发图片给群，没有问题，转发图片给好友，就会报错
不知道是不是mirai-api-http插件的问题，我到mirai-api-http下面提issue
![EHP70TSTP0$Q} N~3)EW_D7](https://user-images.githubusercontent.com/25838633/78019794-d1249600-7382-11ea-8b93-24ac8e869aea.png)

**Comment by Chenwe-i-lin** [comment]
?这咋又开了

**Comment by Chenwe-i-lin** [comment]
,,,,,,,日?我去处理下

**Comment by Chenwe-i-lin** [comment]
最新的 commit 修好了
