### ISSUE TITLE
群组头像问题

### ISSUE THREAD

**Issue by water-lift** [NatriumLab/python-mirai#57]
https://github.com/NatriumLab/python-mirai/blob/986de48541d7a5df87b0e1cab90dc88a91d3dfe0/mirai/entities/group.py#L19

这样获取到的不是最新版本

最新版本的应该是
```python
f'https://p.qlogo.cn/gh/{self.id}/{self.id}/140' 
```

btw那个`140`是限制分辨率的，去掉可以获取更大一点的版本

**Comment by Chenwe-i-lin** [comment]
fixed.
