### ISSUE TITLE
Quote消息组件的类型标注是否有错误？

### ISSUE THREAD

**Issue by Trebor-Huang** [NatriumLab/python-mirai#64]
https://github.com/NatriumLab/python-mirai/blob/03f5da47df4375da47942f8c0e4afbabb09a40e5/mirai/event/message/components.py#L63

请问这里的`origin`为什么是`int`类型？另，希望能解决问题 #59 ，我可以提供帮助。

**Comment by Chenwe-i-lin** [comment]
python **没有** Long 类型, 整数使用 int, 浮点数使用 float, 若要极致精确则用 decimal.

**Comment by Chenwe-i-lin** [comment]
关于 #59 : 我目前由于学业和个人生活原因, 暂时无法对项目本身做非常细致的注解, 我会在我把生活中的害虫全部扫干净后重新参与到 python-mirai 的开发中去.

顺便, 如果你希望对本项目作出贡献, 欢迎发起 Pull Request

**Comment by jinzhijie** [comment]
@Chenwe-i-lin 无法正常使用 quote，请问该传入什么

![image](https://user-images.githubusercontent.com/34389622/87787811-d42e8e00-c86e-11ea-8038-578892f44179.png)

![image](https://user-images.githubusercontent.com/34389622/87787862-edcfd580-c86e-11ea-8441-651339fc6cb0.png)

**Comment by Chenwe-i-lin** [comment]
> @Chenwe-i-lin 无法正常使用 quote，请问该传入什么
> 
> ![image](https://user-images.githubusercontent.com/34389622/87787811-d42e8e00-c86e-11ea-8038-578892f44179.png)
> 
> ![image](https://user-images.githubusercontent.com/34389622/87787862-edcfd580-c86e-11ea-8441-651339fc6cb0.png)

传入 quoteSource 参数

**Comment by jinzhijie** [comment]
> > @Chenwe-i-lin 无法正常使用 quote，请问该传入什么
> > ![image](https://user-images.githubusercontent.com/34389622/87787811-d42e8e00-c86e-11ea-8038-578892f44179.png)
> > ![image](https://user-images.githubusercontent.com/34389622/87787862-edcfd580-c86e-11ea-8441-651339fc6cb0.png)
> 
> 传入 quoteSource 参数

类型是 `mirai.Source`？
