### ISSUE TITLE
怎么转发消息？文档还在更新吗？

### ISSUE THREAD

**Issue by mySaYo** [NatriumLab/python-mirai#80]
两个群之间互通，或者监听别人消息。。。消息中可能包含图片啥的，如果能直接转发那就省事了。（自我标识为低级问题）哪位老哥建个群呗，问无可问即便群里大佬不会回答，日常也能耳濡目染听大佬的问题吧，想拉别人一起来玩这个机器人，然后问他们问题（这个想法使不得）然而他们都是小白，而我尚未入门。

**Comment by Chenwe-i-lin** [comment]
调用方法 sendGroupMessage 时传入参数 quoteMessage，可以直接接上int形式的 messageid 或者是发送消息方法的返回 BotMessage

**Comment by SAGIRI-kawaii** [comment]
> 调用方法 sendGroupMessage 时传入参数 quoteMessage，可以直接接上int形式的 messageid 或者是发送消息方法的返回 BotMessage

![image](https://user-images.githubusercontent.com/45849471/81500449-e0ddb580-9304-11ea-979c-ba2cb73a5b68.png)
![image](https://user-images.githubusercontent.com/45849471/81500465-ee933b00-9304-11ea-8c0c-ecd16ab16967.png)
使用此方法会出现上图情况：ERROR: Protocol: cannot connect to the headless client, will retry after 5 seconds.
想问下如何解决啊

**Comment by Chenwe-i-lin** [comment]
。。。mdzz

**Comment by Chenwe-i-lin** [comment]
预计是 source 对象的问题，0.4.0 会推出 components selector 解决这个问题

**Comment by Chenwe-i-lin** [comment]
？
