### ISSUE TITLE
安卓端能用lua脚本耶。。

### ISSUE THREAD

**Issue by mySaYo** [NatriumLab/python-mirai#81]
要是是py就好了，泪奔，我去入个lua门了

**Comment by GregTechnology** [comment]
mirai项目相关请移步主项目 这里是python sdk 您的issue会造成watcher巨大多不适 谢谢理解
另：我个人不认为安卓上跑python是多聪明的做法 跑起来可能会遇到性能瓶颈

**Comment by mySaYo** [comment]
> mirai项目相关请移步主项目 这里是python sdk 您的issue会造成watcher巨大多不适 谢谢理解
> 另：我个人不认为安卓上跑python是多聪明的做法 跑起来可能会遇到性能瓶颈

赞同，毕竟机器人需要长时间挂着。就像在手机上写代码。。装Linux。。没啥用。但是还是想折腾。

**Comment by Chenwe-i-lin** [comment]
无意义 issue 请自行关闭。
