### ISSUE TITLE
Usage of Dependency with Cache

### ISSUE THREAD

**Issue by NoctiZen** [NatriumLab/python-mirai#94]
Hi,

I have been trying to take advantage of the dependency injection system in this project. I read the examples given in `mirai/utilles/dependencies.py` and managed to write my own dependency which checks if someone is talking to the bot:
```python
def AssertToMe():
    async def to_me_wrapper(app: Mirai, message: MessageChain):
        at_first = message.getFirstComponent(At)
        plain_first = message.getFirstComponent(Plain)
        if at_first and at_first.target == app.qq:
            return
        if plain_first and plain_first.toString().lstrip().startswith(conf.get('basic', 'nick_name')):
            return
        raise Cancelled
    return Depend(to_me_wrapper)
...
@app.receiver("GroupMessage", dependencies=[AssertToMe()])
async def quote(app: Mirai, group: Group, message: MessageChain, member: Member, source: Source):
    await app.sendGroupMessage(group, [Plain("testtest")],
                                quoteSource=source)
    return True
```
It turned out that the dependency function never gets executed. After some debugging I found that turning off the `cache` option fixes the issue: `return Depend(to_me_wrapper, cache = False)`.

I was not sure if it was due to some potential bug in my code, so I checked once again by using the dependency function provided in the project:

```python
from mirai.utilles.dependencies import AssertAt
...
@app.receiver("GroupMessage", dependencies=[AssertAt()])
async def quote(app: Mirai, group: Group, message: MessageChain, member: Member, source: Source):
    await app.sendGroupMessage(group, [Plain("testtest")],
                                quoteSource=source)
    return True
```
Now I am able to get response from the bot no matter I am At-ing it or not. Am I missing something? Please let me know if any further information is required.

**Comment by Chenwe-i-lin** [comment]
do you checked `plain_first and plain_first.toString().lstrip().startswith(conf.get('basic', 'nick_name'))` 's return value? if True, it maybe a bug...

it'll resolve when python-mirai v4 release.

my english is not very good on development field, i can only read some docs, i'm so sorry :(

**Comment by Chenwe-i-lin** [comment]
Depend.cache will use `DecoraterInterface.localStorage` in python-mirai v4, it'll be fixed.

**Comment by Chenwe-i-lin** [comment]
fixed in graia-broadcast.
