### ISSUE TITLE
[功能提议]请问有没有开发NLP装饰器的计划？

### ISSUE THREAD

**Issue by zdf0221** [NatriumLab/python-mirai#95]
如题，从[Nonebot](https://nonebot.cqp.moe/)搬迁而来，这个项目好顶赞。但是发现这个Python框架暂时还没有实现类似NLP装饰器的功能，请问未来有没有后续的开发计划？谢谢

**Comment by zdf0221** [comment]
又仔细研究了下文档，感觉依赖注入可能是实现的手段之一，自行实现自然语言处理器，然后作为依赖传递给GroupMessageHandler。
另外感觉文档很久不更新了，有一些已经deprecate的语法还残留在文档中，例如Session, EventContextBody, 不知道是不是我找的不仔细，看了源码没找到相关的实现。

**Comment by Chenwe-i-lin** [comment]
文档已经好久都没更新了...

NLP 装饰器非常有可能作为一个单独模块, 不过这对我来说是次要性实现的, 你可以先用 Depend 实现, pym v4 的 Depend 使用 BroadcastControl 的 Decorate 机制实现, 设计上是兼容 v3 的写法的.

**Comment by Chenwe-i-lin** [comment]
本功能交与社区进行开发, 我没有打算做这玩意的想法, 因为我没有使用过这方面的功能

**Comment by Chenwe-i-lin** [comment]
建议社区开发时使用 `graia-nlp` 作为包名, 由于 pym v4 使用了 namespace package, 强烈建议使用 poetry.
