### ISSUE TITLE
BotJoinGroupEvent貌似在tim上不能正常触发

### ISSUE THREAD

**Issue by zdf0221** [NatriumLab/python-mirai#96]
RT, 测试环境是Windows 10 X64， 测试了bot被动邀请与主动加入群，log中均无BotJoinGroupEvent的触发事件。Mirai-console中有正常的事件触发。但Raise NoSuchElementException Error

截取部分exception log如下，猜测可能是群号匹配问题导致，核查群号无问题，替代测试其他群，该问题能够重现。
![image](https://user-images.githubusercontent.com/9160607/84714837-dbdfd780-af3c-11ea-87a6-145cfc37d0e9.png)

**Comment by Chenwe-i-lin** [comment]
这不属于 python-mirai 的问题, 建议前往 [mirai-core 的 issue 区](https://github.com/mamoe/mirai/issues).

**Comment by Chenwe-i-lin** [comment]
顺便: TIM 怎么老是出问题...
