### ISSUE TITLE
关于文档中的教程中的测试程序helloworld无法通过电脑qq进行触发

### ISSUE THREAD

**Issue by xiaofentai** [NatriumLab/python-mirai#97]
您好，我是一枚python小白，基本通过教程中的测试程序进行学习如何开发，过程中发现这个测试程序无法通过电脑qq进行触发，手机这边就行，也出现过 Issues里其他人提到的图片开裂问题（好像是无解）。请问这无法用电脑qq触发的问题要如何解决？（如果我的问题过于简单，我深感抱歉。）

**Comment by Chenwe-i-lin** [comment]
我几个月前写的屎山还有人用?

不知道你的情况是如何, 文档内的教程理论上没有任何问题, 检查你自身的原因(例如不小心把 mirai-console 的控制台选中导致进程暂停)
